apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app: frontend 