apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dnd-campaign-organizer-dev

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: api
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: discord-bot

configMapGenerator:
  - name: dnd-app-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - REACT_APP_API_URL=http://api-service:4000

images:
  - name: dnd-campaign-organizer-frontend
    newTag: dev
  - name: dnd-campaign-organizer-api
    newTag: dev
  - name: dnd-campaign-organizer-discord-bot
    newTag: dev 