name: Test Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Build all packages
      run: npm run build
      
    - name: Check TypeScript compilation
      run: |
        cd apps/api && npx tsc --noEmit
        cd ../frontend && npx tsc --noEmit
        cd ../discord-bot && npx tsc --noEmit
        
    - name: Test Docker builds (without pushing)
      run: |
        docker build -f apps/frontend/Dockerfile . --tag test-frontend
        docker build -f apps/api/Dockerfile . --tag test-api
        docker build -f apps/discord-bot/Dockerfile . --tag test-discord-bot
        
    - name: Verify Docker images
      run: |
        docker images | grep test-
        echo "✅ All Docker images built successfully!" 